# -*- coding: utf-8 -*-

print "%s\t\t%s" % ("print", "escreve uma string no console.")
print "%s\t\t%s" % ("#", "comentário, o interpretador ignora tudo a direita.")
print "%s\t\t%s" % ("+", "adição. contatenação de strings.")
print "%s\t\t%s" % ("/", "divisão.")
print "%s\t\t%s" % ("*", "multiplicação.")
print "%s\t\t%s" % ("%", "resto da divisão.")
print "%s\t\t%s" % ("-", "subtração.")
print "%s\t\t%s" % ("<", "menor que.")
print "%s\t\t%s" % (">", "maior que.")
print "%s\t\t%s" % ("<=", "menor ou igual que.")
print "%s\t\t%s" % (">=", "maior ou igual que.")
print "%s\t\t%s" % ("=", "atribuição de valores")
print "%s\t\t%s" % ("'", "aspas simples. definição de string.")
print "%s\t\t%s" % ('"', "aspas suplas. definição de string.")
print "%s\t\t%s" % ("\\n", "caractere de quebra de linha.")
print "%s\t\t%s" % ("\\t", "caractere de tabulação.")
print "%s\t%s" % ("raw_input", "aguarda uma entrada do usuário pelo teclado.")
print "%s\t\t%s" % ("from", "define a biblioteca a ser importada.")
print "%s\t\t%s" % ("import", "define o(s) recursos da biblioteca a ser importada.")
print "%s\t\t%s" % ("open", "abre um arquivo e retorna uma referência a um objeto file")
print "%s\t\t%s" % ("read", "le um determinado conjunto de bytes do arquivo")
print "%s\t\t%s" % ("close", "fecha a referência ao arquivo.")
print "%s\t%s" % ("truncate", "zera o conteúdo do arquivo.")
print "%s\t\t%s" % ("write", "grava dados ao arquivo.")
print "%s\t\t%s" % ("def", "define um método")
print "%s\t\t%s" % ("seek", "posiciona o leitor em um determinado ponto do arquivo")
print "%s\t%s" % ("readline", "le uma linha inteira do arquivo")
print "%s\t\t%s" % ("+=", "incrementa / concatena dados a uma variável")